# Generated by Django 2.2 on 2020-06-12 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('coding_dojo_wall', '0002_auto_20200612_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='login.User'),
            preserve_default=False,
        ),
    ]
