# Generated by Django 2.2 on 2020-06-05 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='desc',
            new_name='description',
        ),
    ]
