# Generated by Django 2.2 on 2020-06-06 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20200605_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
